### Modeling Loan Repayment Behavior and Cash Flow
Goals: Replicating Article given Loan Transition Model outputs and creating function in Cash Engine for amortization matrix given 1) number of installments for loan (i) and 2) current time (t)


In [450]:
import pandas as pd
import numpy as np

In [451]:
#Inputting initial information, table 2 and table 4 of the article
np_ltm_transition_matrix = np.array([[0.895, 0.04,0,0,0,0.005,0.06],[0, 0,1,0,0,0,0],[0, 0,0,1,0,0,0],
                     [0, 0,0,0,1,0,0],[0, 0,0,0,0,1,0],[0, 0,0,0,0,1,0],
                    [0, 0,0,0,0,0,1],])

ltm_transition_matrix = pd.DataFrame(data=np_ltm_transition_matrix, index=["current", "dq1-30","d31-60", "d61-90","dq91-120", "charged off","paid off"], 
                  columns=["current", "dq1-30","d31-60","d61-90","dq91-120","charged off","paid off"])
print(ltm_transition_matrix)
np_current_loan_state = np.array([[100],[0],[0],[0],[0],[0],[0]])

             current  dq1-30  d31-60  d61-90  dq91-120  charged off  paid off
current        0.895    0.04     0.0     0.0       0.0        0.005      0.06
dq1-30         0.000    0.00     1.0     0.0       0.0        0.000      0.00
d31-60         0.000    0.00     0.0     1.0       0.0        0.000      0.00
d61-90         0.000    0.00     0.0     0.0       1.0        0.000      0.00
dq91-120       0.000    0.00     0.0     0.0       0.0        1.000      0.00
charged off    0.000    0.00     0.0     0.0       0.0        1.000      0.00
paid off       0.000    0.00     0.0     0.0       0.0        0.000      1.00


In [452]:
np_current_loan_state

array([[100],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0]])

In [453]:
row_wise_multiplication = np_current_loan_state*np_ltm_transition_matrix

In [454]:
#Table 5
row_wise_multiplication

array([[89.5,  4. ,  0. ,  0. ,  0. ,  0.5,  6. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [455]:
prob_weighted_matrix = row_wise_multiplication*amortization_matrix(1,3)

In [456]:
#Table 6
prob_weighted_matrix

array([[59.66666667,  4.        ,  0.        ,  0.        ,  0.        ,
         0.5       ,  6.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [457]:
#Table 6 - cash flows for t = 1
sum_columns = np.array([sum(x) for x in zip(*prob_weighted_matrix)])
sum_columns = sum_columns.reshape(-1, 1)

In [458]:
#Inputting output of LTM for t=2
np_ltm_transition_matrix_2 = np.array([[0.895, 0.04,0,0,0,0.005,0.06],[0.24, 0.34,0.4,0,0,0,0.02],[0, 0,0,1,0,0,0],
                     [0, 0,0,0,1,0,0],[0, 0,0,0,0,1,0],[0, 0,0,0,0,1,0],
                    [0, 0,0,0,0,0,1],])

#Table 7
row_wise_multiplication_2 = sum_columns*np_ltm_transition_matrix_2
row_wise_multiplication_2

array([[53.40166667,  2.38666667,  0.        ,  0.        ,  0.        ,
         0.29833333,  3.58      ],
       [ 0.96      ,  1.36      ,  1.6       ,  0.        ,  0.        ,
         0.        ,  0.08      ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  6.        ]])

In [459]:
prob_weighted_matrix_2 = row_wise_multiplication_2*amortization_matrix(2,3)

In [460]:
#Table 7
prob_weighted_matrix_2

array([[26.70083333,  2.38666667,  0.        ,  0.        ,  0.        ,
         0.29833333,  3.58      ],
       [ 0.32      ,  0.90666667,  1.6       ,  0.        ,  0.        ,
         0.        ,  0.08      ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  6.        ]])

In [461]:
sum_columns_2 = np.array([sum(x) for x in zip(*prob_weighted_matrix_2)])
sum_columns_2 = sum_columns_2.reshape(-1, 1)

In [462]:
#Table 7 - sum of cash flows
sum_columns_2

array([[27.02083333],
       [ 3.29333333],
       [ 1.6       ],
       [ 0.        ],
       [ 0.        ],
       [ 0.79833333],
       [ 9.66      ]])

In [463]:
# The function below supports the Cash Engine by generating the amortization matrix for any time t and number of installments i 
#in zero-interest loans
def amortization_matrix(time, num_installments):
    #Logic for current to other states, given time-step t, number of installments i
    #0.6667 = t 1
    #0.5000 = t 2
    #(1-2/3*p)/(1-1/3*p)
    #(3/3)(2/3)/(3/3)-(1/3)
    #1/3/2/3=1/2
    i = num_installments
    t = time
    
    sub = 0 if t-1 < 0 else min(t-1,i)
    z = 1 - (sub / i)
    try:
        cu_to_cu = max(min((1-t/i)/z,1),0)
        cu_to_dq1 = max(min((1-(t-1)/i)/z,1),0)
        cu_to_dq31 = max(min((1-(t-2)/i)/z,1),0)
        cu_to_dq61 = max(min((1-(t-3)/i)/z,1),0)
        cu_to_dq91 = max(min((1-(t-4)/i)/z,1),0)
    except ZeroDivisionError:
        cu_to_cu = 0
        cu_to_dq1 = 0
        cu_to_dq31 = 0
        cu_to_dq61 = 0
        cu_to_dq91 = 0   

    cu_to_co = 1
    cu_to_po = 1
    
    #Logic for dq1 to other states, given time-step t, number of installments i
    sub = 0 if t-2 < 0 else min(t-2,i)
    z = 1 - (sub / i)
    try:
        dq1_to_cu = max(min((1-t/i)/z,1),0)
        dq1_to_dq1 = max(min((1-(t-1)/i)/z,1),0)
        dq1_to_dq31 = max(min((1-(t-2)/i)/z,1),0)
        dq1_to_dq61 = max(min((1-(t-3)/i)/z,1),0)
        dq1_to_dq91 = max(min((1-(t-4)/i)/z,1),0)
    except ZeroDivisionError:
        dq1_to_cu = 0
        dq1_to_dq1 = 0
        dq1_to_dq31 = 0
        dq1_to_dq61 = 0
        dq1_to_dq91 = 0

    dq1_to_co = 1
    dq1_to_po = 1
    
    #Logic for dq1 to other states, given time-step t, number of installments i
    sub = 0 if t-3 < 0 else min(t-3,i)
    z = 1 - (sub / i)
    try:
        dq31_to_cu = max(min((1-t/i)/z,1),0)
        dq31_to_dq1 = max(min((1-(t-1)/i)/z,1),0)
        dq31_to_dq31 = max(min((1-(t-2)/i)/z,1),0)
        dq31_to_dq61 = max(min((1-(t-3)/i)/z,1),0)
        dq31_to_dq91 = max(min((1-(t-4)/i)/z,1),0)
    except ZeroDivisionError:
        dq31_to_cu = 0
        dq31_to_dq1 = 0
        dq31_to_dq31 = 0
        dq31_to_dq61 = 0
        dq31_to_dq91 = 0

    dq31_to_co = 1
    dq31_to_po = 1
    
    #Logic for dq1 to other states, given time-step t, number of installments i
    sub = 0 if t-4 < 0 else min(t-4,i)
    z = 1 - (sub / i)
    try:
        dq61_to_cu = max(min((1-t/i)/z,1),0)
        dq61_to_dq1 = max(min((1-(t-1)/i)/z,1),0)
        dq61_to_dq31 = max(min((1-(t-2)/i)/z,1),0)
        dq61_to_dq61 = max(min((1-(t-3)/i)/z,1),0)
        dq61_to_dq91 = max(min((1-(t-4)/i)/z,1),0)
    except ZeroDivisionError:
        dq61_to_cu = 0
        dq61_to_dq1 = 0
        dq61_to_dq31 = 0
        dq61_to_dq61 = 0
        dq61_to_dq91 = 0

    dq61_to_co = 1
    dq61_to_po = 1
    
    #Logic for dq1 to other states, given time-step t, number of installments i
    sub = 0 if t-5 < 0 else min(t-5,i)
    z = 1 - (sub / i)
    try:
        dq91_to_cu = max(min((1-t/i)/z,1),0)
        dq91_to_dq1 = max(min((1-(t-1)/i)/z,1),0)
        dq91_to_dq31 = max(min((1-(t-2)/i)/z,1),0)
        dq91_to_dq61 = max(min((1-(t-3)/i)/z,1),0)
        dq91_to_dq91 = max(min((1-(t-4)/i)/z,1),0)
    except ZeroDivisionError:
        dq91_to_cu = 0
        dq91_to_dq1 = 0
        dq91_to_dq31 = 0
        dq91_to_dq61 = 0
        dq91_to_dq91 = 0
    dq91_to_co = 1
    dq91_to_po = 1
    
    np_mortization_matrix = np.array([[cu_to_cu, cu_to_dq1,cu_to_dq31,cu_to_dq61,cu_to_dq91,cu_to_co,cu_to_po],[dq1_to_cu, dq1_to_dq1,dq1_to_dq31,dq1_to_dq61,dq1_to_dq91,dq1_to_co,dq1_to_po],[dq31_to_cu, dq31_to_dq1, dq31_to_dq31, dq31_to_dq61, dq31_to_dq91, dq31_to_co, dq31_to_po],
                     [dq61_to_cu, dq61_to_dq1, dq61_to_dq31, dq61_to_dq61, dq61_to_dq91, dq61_to_co, dq61_to_po],[dq91_to_cu, dq91_to_dq1, dq91_to_dq31, dq91_to_dq61, dq91_to_dq91, dq91_to_co, dq91_to_po],
                     [1, 1, 1, 1, 1, 1, 1],[1, 1, 1, 1, 1, 1, 1],])
    return np_mortization_matrix

In [464]:
amortization_matrix(2,3)

array([[0.5       , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.33333333, 0.66666667, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.33333333, 0.66666667, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.33333333, 0.66666667, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.33333333, 0.66666667, 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]])